/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FeaturedPlayersRouteImport } from './routes/featured-players'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WellnessHubIndexRouteImport } from './routes/wellness-hub.index'
import { Route as StoriesIndexRouteImport } from './routes/stories.index'
import { Route as WellnessHubArticleSlugRouteImport } from './routes/wellness-hub.$articleSlug'
import { Route as StoriesStoryIdRouteImport } from './routes/stories.$storyId'
import { Route as RegisterSuccessRouteImport } from './routes/register.success'
import { Route as RegisterScoutRouteImport } from './routes/register.scout'
import { Route as RegisterAthleteRouteImport } from './routes/register.athlete'
import { Route as PlayersPlayerIdRouteImport } from './routes/players.$playerId'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturedPlayersRoute = FeaturedPlayersRouteImport.update({
  id: '/featured-players',
  path: '/featured-players',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WellnessHubIndexRoute = WellnessHubIndexRouteImport.update({
  id: '/wellness-hub/',
  path: '/wellness-hub/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const WellnessHubArticleSlugRoute = WellnessHubArticleSlugRouteImport.update({
  id: '/wellness-hub/$articleSlug',
  path: '/wellness-hub/$articleSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryIdRoute = StoriesStoryIdRouteImport.update({
  id: '/stories/$storyId',
  path: '/stories/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSuccessRoute = RegisterSuccessRouteImport.update({
  id: '/register/success',
  path: '/register/success',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterScoutRoute = RegisterScoutRouteImport.update({
  id: '/register/scout',
  path: '/register/scout',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterAthleteRoute = RegisterAthleteRouteImport.update({
  id: '/register/athlete',
  path: '/register/athlete',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clubs': typeof ClubsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/featured-players': typeof FeaturedPlayersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/register/athlete': typeof RegisterAthleteRoute
  '/register/scout': typeof RegisterScoutRoute
  '/register/success': typeof RegisterSuccessRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/wellness-hub/$articleSlug': typeof WellnessHubArticleSlugRoute
  '/stories/': typeof StoriesIndexRoute
  '/wellness-hub/': typeof WellnessHubIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clubs': typeof ClubsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/featured-players': typeof FeaturedPlayersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/register/athlete': typeof RegisterAthleteRoute
  '/register/scout': typeof RegisterScoutRoute
  '/register/success': typeof RegisterSuccessRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/wellness-hub/$articleSlug': typeof WellnessHubArticleSlugRoute
  '/stories': typeof StoriesIndexRoute
  '/wellness-hub': typeof WellnessHubIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clubs': typeof ClubsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/featured-players': typeof FeaturedPlayersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/register/athlete': typeof RegisterAthleteRoute
  '/register/scout': typeof RegisterScoutRoute
  '/register/success': typeof RegisterSuccessRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/wellness-hub/$articleSlug': typeof WellnessHubArticleSlugRoute
  '/stories/': typeof StoriesIndexRoute
  '/wellness-hub/': typeof WellnessHubIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clubs'
    | '/dashboard'
    | '/featured-players'
    | '/how-it-works'
    | '/login'
    | '/dashboard/admin'
    | '/players/$playerId'
    | '/register/athlete'
    | '/register/scout'
    | '/register/success'
    | '/stories/$storyId'
    | '/wellness-hub/$articleSlug'
    | '/stories/'
    | '/wellness-hub/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clubs'
    | '/dashboard'
    | '/featured-players'
    | '/how-it-works'
    | '/login'
    | '/dashboard/admin'
    | '/players/$playerId'
    | '/register/athlete'
    | '/register/scout'
    | '/register/success'
    | '/stories/$storyId'
    | '/wellness-hub/$articleSlug'
    | '/stories'
    | '/wellness-hub'
  id:
    | '__root__'
    | '/'
    | '/clubs'
    | '/dashboard'
    | '/featured-players'
    | '/how-it-works'
    | '/login'
    | '/dashboard/admin'
    | '/players/$playerId'
    | '/register/athlete'
    | '/register/scout'
    | '/register/success'
    | '/stories/$storyId'
    | '/wellness-hub/$articleSlug'
    | '/stories/'
    | '/wellness-hub/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClubsRoute: typeof ClubsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FeaturedPlayersRoute: typeof FeaturedPlayersRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  RegisterAthleteRoute: typeof RegisterAthleteRoute
  RegisterScoutRoute: typeof RegisterScoutRoute
  RegisterSuccessRoute: typeof RegisterSuccessRoute
  StoriesStoryIdRoute: typeof StoriesStoryIdRoute
  WellnessHubArticleSlugRoute: typeof WellnessHubArticleSlugRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
  WellnessHubIndexRoute: typeof WellnessHubIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/featured-players': {
      id: '/featured-players'
      path: '/featured-players'
      fullPath: '/featured-players'
      preLoaderRoute: typeof FeaturedPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellness-hub/': {
      id: '/wellness-hub/'
      path: '/wellness-hub'
      fullPath: '/wellness-hub/'
      preLoaderRoute: typeof WellnessHubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellness-hub/$articleSlug': {
      id: '/wellness-hub/$articleSlug'
      path: '/wellness-hub/$articleSlug'
      fullPath: '/wellness-hub/$articleSlug'
      preLoaderRoute: typeof WellnessHubArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId': {
      id: '/stories/$storyId'
      path: '/stories/$storyId'
      fullPath: '/stories/$storyId'
      preLoaderRoute: typeof StoriesStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/success': {
      id: '/register/success'
      path: '/register/success'
      fullPath: '/register/success'
      preLoaderRoute: typeof RegisterSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/scout': {
      id: '/register/scout'
      path: '/register/scout'
      fullPath: '/register/scout'
      preLoaderRoute: typeof RegisterScoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/athlete': {
      id: '/register/athlete'
      path: '/register/athlete'
      fullPath: '/register/athlete'
      preLoaderRoute: typeof RegisterAthleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClubsRoute: ClubsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FeaturedPlayersRoute: FeaturedPlayersRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  RegisterAthleteRoute: RegisterAthleteRoute,
  RegisterScoutRoute: RegisterScoutRoute,
  RegisterSuccessRoute: RegisterSuccessRoute,
  StoriesStoryIdRoute: StoriesStoryIdRoute,
  WellnessHubArticleSlugRoute: WellnessHubArticleSlugRoute,
  StoriesIndexRoute: StoriesIndexRoute,
  WellnessHubIndexRoute: WellnessHubIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
